EXTRA_CFLAGS += -DHRD_OS_LINUX -DHRD_ENDNESS_LITTLE -DBOARD_TYPE_CHIP -I$(src)/../include  -Wno-format-extra-args -Wno-error=date-time

obj-$(CONFIG_HI_NET_MDIO)	+= iware_mdio_main.o  iware_mdio_hal.o

